/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jacky_uitest_utils_OcrUtil */

#ifndef _Included_com_jacky_uitest_utils_OcrUtil
#define _Included_com_jacky_uitest_utils_OcrUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jacky_uitest_utils_OcrUtil
 * Method:    getBinaryBitmap
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jacky_uitest_utils_OcrUtil_getBinaryBitmap
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
